import Link from "next/link";
import { contactCategories } from "@/data/contact";
import { siteConfig } from "@/data/site";
import { Reveal } from "@/components/ui/reveal";

export function Contact() {
  return (
    <section id="contact" aria-labelledby="contact-title" className="contact-signal border-t border-white/10 px-5 py-24 sm:px-8 sm:py-32">
      <Reveal className="mx-auto max-w-[90rem]">
        <div className="grid gap-12 border-y border-white/15 py-14 lg:grid-cols-[1.15fr_0.85fr] lg:items-end">
          <div><p className="text-xs font-black uppercase tracking-[0.34em] text-[#35d0e5]">Open channel / Contact</p><h2 id="contact-title" className="mt-6 max-w-4xl text-5xl font-black leading-[0.96] tracking-[-0.04em] text-white sm:text-7xl">Let&apos;s build something meaningful.</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">Für Recruiting-Projekte, Interviews, kreative Kooperationen, Plattformideen oder Gespräche über Arbeit, Menschen und Entwicklung.</p><nav aria-label="Projekte im Digital HQ" className="mt-9 flex flex-wrap gap-3"><Link href="/projects/goatrecrutainer" className="inline-flex min-h-12 items-center rounded-full bg-[#35d0e5] px-6 py-3 font-black text-[#041018] transition hover:-translate-y-0.5 hover:bg-[#73e3f1]">GOATRECRUTAINER entdecken →</Link><Link href="/projects/ratecom" className="inline-flex min-h-12 items-center rounded-full border border-white/20 px-6 py-3 font-black text-white transition hover:-translate-y-0.5 hover:border-[#ff9a3d]">RateCom entdecken →</Link></nav></div>
          <div><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#ff9a3d]">Possible intersections</p><ul className="mt-5 grid gap-2">{contactCategories.map((category, index) => <li key={category} className="flex items-center gap-4 border-b border-white/10 py-3 font-bold text-slate-200"><span className="font-mono text-xs text-slate-600">0{index + 1}</span>{category}</li>)}</ul></div>
        </div>
        <div className="mt-8 grid gap-5 lg:grid-cols-[1.25fr_0.75fr]">
          <section aria-labelledby="social-title" className="rounded-[1.75rem] border border-white/10 bg-[#071824]/75 p-6 sm:p-8"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#35d0e5]">Social presence</p><h3 id="social-title" className="mt-4 text-2xl font-black text-white">Follow the work where it lives.</h3><p className="mt-3 max-w-2xl leading-7 text-slate-400">Karrieregeschichten und GOATRECRUTAINER-Formate auf TikTok, Instagram und YouTube — Benjamins professionelles Profil auf LinkedIn.</p><ul className="mt-7 grid gap-3 sm:grid-cols-2">{siteConfig.socialLinks.map((social) => <li key={social.label}><a href={social.url} target="_blank" rel="noopener noreferrer" aria-label={`${social.label} – ${social.context} (externe Website, öffnet in neuem Tab)`} className="group flex min-h-16 items-center justify-between gap-4 rounded-2xl border border-white/15 px-5 py-3 transition hover:border-[#35d0e5]/55 hover:bg-white/[0.035]"><span><strong className="block text-white">{social.label}</strong><span className="mt-1 block text-xs text-slate-500">{social.context}</span></span><span className="shrink-0 font-mono text-[10px] uppercase tracking-[0.14em] text-[#35d0e5]">External ↗</span></a></li>)}</ul></section>
          <section aria-labelledby="booking-title" className="rounded-[1.75rem] border border-[#ff9a3d]/25 bg-[#ff9a3d]/[0.045] p-6 sm:p-8"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#ff9a3d]">Booking</p><h3 id="booking-title" className="mt-4 text-2xl font-black text-white">A conversation with context.</h3><p className="mt-3 leading-7 text-slate-400">Die Terminbuchung wird hier freigeschaltet, sobald der öffentliche Buchungslink verifiziert ist.</p>{siteConfig.booking.url ? <a href={siteConfig.booking.url} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex min-h-12 items-center rounded-full bg-[#ff9a3d] px-6 py-3 font-black text-[#041018] transition hover:-translate-y-0.5">{siteConfig.booking.label} · Extern ↗</a> : <div role="status" className="mt-7 border-l-2 border-[#ff9a3d] pl-4"><p className="font-black text-white">{siteConfig.booking.label}</p><p className="mt-1 text-sm leading-6 text-slate-400">Öffentlicher Link in Verifizierung — noch keine Buchung möglich.</p></div>}</section>
        </div>
      </Reveal>
    </section>
  );
}
