import type { Metadata } from "next";
import Link from "next/link";

import { siteConfig } from "@/data/site";
import { newsletterControllerAddress } from "@/lib/newsletter/config";

export const metadata: Metadata = { title: "Privacy | bts.online", description: "Privacy information for bts.online services.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  const controllerAddress = newsletterControllerAddress();
  return <article className="px-5 pb-24 pt-28 sm:px-8 sm:pt-36"><div className="mx-auto max-w-4xl"><nav aria-label="Breadcrumb" className="font-mono text-xs text-slate-400"><Link href="/" className="inline-flex min-h-11 items-center hover:text-white">Digital HQ</Link> / <span aria-current="page" className="text-[#35d0e5]">Privacy</span></nav><header className="border-b border-white/15 py-14"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#35d0e5]">Privacy / Clear boundaries</p><h1 className="mt-5 text-5xl font-black text-white sm:text-7xl">Your data should have a reason to be here.</h1></header><section id="newsletter" aria-labelledby="newsletter-privacy-title" className="scroll-mt-28 py-14"><h2 id="newsletter-privacy-title" className="text-3xl font-black text-white">Newsletter</h2>{controllerAddress ? <><p className="mt-5 leading-7 text-slate-300">Controller: {siteConfig.name}, <span className="whitespace-pre-line">{controllerAddress}</span>. Privacy contact: <a className="text-[#35d0e5] underline underline-offset-4" href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>.</p><p className="mt-5 leading-7 text-slate-300">The newsletter stores the email address, a pseudonymous keyed email hash, subscription status, consent version and timestamps, token hashes, and short-lived pseudonymous abuse-control data. The legal basis for newsletter delivery is explicit consent. Confirmation messages are used only to complete the requested double opt-in.</p><p className="mt-5 leading-7 text-slate-300">Brevo is the intended email processor. Confirmed subscribers receive New Writing and occasional updates from the Digital HQ, with no fixed schedule. Every edition provides an unsubscribe route. Newsletter consent is separate from BTS Account.</p><p className="mt-5 leading-7 text-slate-300">Unconfirmed pending subscriptions are scheduled for cleanup after seven days. Final Production retention periods for consent evidence and suppression records must be documented before collection is enabled. No open or click tracking is part of Newsletter V1.</p></> : <div role="status" className="mt-6 border-l-2 border-[#ff9a3d] p-6"><p className="font-bold text-white">Newsletter collection is not enabled.</p><p className="mt-2 leading-7 text-slate-400">Required controller address and final legal particulars have not been configured. The subscription form remains unavailable until they are supplied.</p></div>}</section></div></article>;
}
