"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

import { ResultFeedback } from "@/components/feedback/result-feedback";
import { MoneyProfileShareDialog } from "@/components/money-profile/money-profile-share-dialog";
import { getMoneyProfileUiCopy } from "@/data/money-profile-locales";
import { moneyChapters, moneyMeaningLabels, moneyStressResponseLabels } from "@/data/money-profile";
import type { Locale } from "@/lib/i18n/config";
import { localizeHref } from "@/lib/i18n/routing";
import { emitMoneyProfileEvent } from "@/lib/money-profile-analytics";
import { deriveMoneyProfile, generateMoneyCalibrationHypotheses, getVisibleMoneyQuestions, reconcileMoneyAnswers } from "@/lib/money-profile-engine";
import { clearMoneyProfileState, readMoneyProfileState, writeMoneyProfileState } from "@/lib/money-profile-persistence";
import type { MoneyAnswer, MoneyCalibration, MoneyCalibrationValue, MoneyProfileResult, MoneyQuestion, PersistedMoneyProfileState } from "@/types/money-profile";

type Phase = "intro" | PersistedMoneyProfileState["phase"];

export function MoneyProfileExperience({ formToken, locale }: { formToken: string | null; locale: Locale }) {
  const copy = getMoneyProfileUiCopy(locale);
  const [phase, setPhase] = useState<Phase>("intro");
  const [answers, setAnswers] = useState<Record<string, MoneyAnswer>>({});
  const [calibration, setCalibration] = useState<Record<string, MoneyCalibrationValue>>({});
  const [currentQuestionId, setCurrentQuestionId] = useState<string | null>("m1");
  const [resumeState, setResumeState] = useState<PersistedMoneyProfileState | null>(null);
  const [persistEnabled, setPersistEnabled] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [selectedExperiment, setSelectedExperiment] = useState(false);
  const activeQuestions = useMemo(() => getVisibleMoneyQuestions(answers), [answers]);
  const currentIndex = Math.max(0, activeQuestions.findIndex(({ id }) => id === currentQuestionId));
  const question = activeQuestions[currentIndex];
  const hypotheses = useMemo(() => generateMoneyCalibrationHypotheses(answers), [answers]);
  const result = useMemo(() => deriveMoneyProfile(answers, calibration), [answers, calibration]);

  useEffect(() => {
    const timer = window.setTimeout(() => { setResumeState(readMoneyProfileState()); setHydrated(true); }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  useEffect(() => {
    if (!hydrated || !persistEnabled || phase === "intro") return;
    writeMoneyProfileState({
      schemaVersion: 1,
      phase,
      questionId: phase === "questions" ? question?.id ?? null : null,
      answers,
      calibration,
      updatedAt: new Date().toISOString(),
      ...(phase === "result" ? { completedAt: new Date().toISOString() } : {}),
    });
  }, [answers, calibration, hydrated, persistEnabled, phase, question?.id]);

  const startFresh = () => {
    clearMoneyProfileState(); setAnswers({}); setCalibration({}); setCurrentQuestionId("m1"); setPersistEnabled(true); setResumeState(null); setSelectedExperiment(false); setPhase("questions"); emitMoneyProfileEvent("money_profile_started");
  };
  const resume = () => {
    if (!resumeState) return startFresh();
    const clean = reconcileMoneyAnswers(resumeState.answers);
    setAnswers(clean); setCalibration(resumeState.calibration); setCurrentQuestionId(resumeState.questionId ?? getVisibleMoneyQuestions(clean)[0]?.id ?? "m1"); setPersistEnabled(true); setPhase(resumeState.phase); emitMoneyProfileEvent("money_profile_resumed");
  };
  const reset = () => { if (window.confirm(copy.resetConfirm)) startFresh(); };

  if (phase === "intro") return <MoneyIntro copy={copy} locale={locale} resumeState={resumeState} onResume={resume} onStart={startFresh} />;
  if (phase === "questions" && question) return <MoneyQuestionView copy={copy} question={question} answer={answers[question.id]} currentIndex={currentIndex} total={activeQuestions.length} onAnswer={(answer) => setAnswers((current) => reconcileMoneyAnswers({ ...current, [question.id]: answer }))} onBack={() => { if (currentIndex > 0) setCurrentQuestionId(activeQuestions[currentIndex - 1].id); }} onNext={() => {
    const nextQuestions = getVisibleMoneyQuestions(answers); const index = nextQuestions.findIndex(({ id }) => id === question.id); const next = nextQuestions[index + 1];
    if (next) { if (next.chapter !== question.chapter) emitMoneyProfileEvent("money_profile_chapter_completed"); setCurrentQuestionId(next.id); }
    else setPhase("calibration");
  }} onSkip={() => { setAnswers((current) => reconcileMoneyAnswers({ ...current, [question.id]: { value: "", skipped: true } })); const next = activeQuestions[currentIndex + 1]; if (next) setCurrentQuestionId(next.id); else setPhase("calibration"); }} onReset={reset} />;
  if (phase === "calibration") return <MoneyCalibrationView calibration={calibration} copy={copy} hypotheses={hypotheses} onBack={() => { setPhase("questions"); setCurrentQuestionId(activeQuestions.at(-1)?.id ?? "m1"); }} onChange={(id, value) => setCalibration((current) => ({ ...current, [id]: value }))} onContinue={() => setPhase("reveal")} onReset={reset} />;
  if (phase === "reveal") return <MoneyReveal copy={copy} onReveal={() => { setPhase("result"); emitMoneyProfileEvent("money_profile_completed"); emitMoneyProfileEvent("money_profile_result_viewed"); }} />;
  return <MoneyResult copy={copy} formToken={formToken} locale={locale} result={result} selectedExperiment={selectedExperiment} onSelectExperiment={() => { setSelectedExperiment((current) => !current); emitMoneyProfileEvent("money_profile_experiment_selected"); }} onRetake={reset} onShare={() => setShareOpen(true)} shareOpen={shareOpen} onShareClose={() => setShareOpen(false)} />;
}

function MoneyIntro({ copy, locale, onResume, onStart, resumeState }: { copy: ReturnType<typeof getMoneyProfileUiCopy>; locale: Locale; onResume: () => void; onStart: () => void; resumeState: PersistedMoneyProfileState | null }) {
  return <article className="section-lines relative overflow-hidden px-5 pb-24 pt-28 sm:px-8 sm:pt-36"><div aria-hidden="true" className="absolute inset-x-0 top-0 h-[72rem] bg-[radial-gradient(circle_at_78%_12%,rgba(184,165,255,.14),transparent_30rem),radial-gradient(circle_at_15%_38%,rgba(255,154,61,.1),transparent_24rem)]" /><div className="relative mx-auto max-w-[90rem]">
    <header className="grid min-h-[70svh] content-center border-b border-white/15 py-16"><p className="font-mono text-xs font-black uppercase tracking-[.26em] text-[#b8a5ff]">BTS.ONLINE / MONEY PROFILE</p><h1 className="mt-7 max-w-6xl text-[clamp(4rem,10vw,9rem)] font-black leading-[.86] tracking-[-.07em] text-white">{copy.publicTitle}</h1><p className="mt-8 max-w-3xl text-2xl font-bold leading-10 text-slate-200">{copy.subtitle}</p><div className="mt-8 flex flex-wrap gap-3 font-mono text-xs text-slate-400"><span>{copy.duration}</span><span aria-hidden="true">·</span><span>{copy.depth}</span><span aria-hidden="true">·</span><span>{copy.noData}</span></div><div className="mt-10 flex flex-wrap gap-3"><button onClick={onStart} className="min-h-14 rounded-full bg-[#b8a5ff] px-8 text-lg font-black text-[#041018]">{copy.cta} →</button>{resumeState ? <button onClick={onResume} className="min-h-14 rounded-full border border-white/15 px-7 font-bold text-white">{copy.resume}</button> : null}</div></header>
    <section className="grid gap-10 border-b border-white/15 py-20 lg:grid-cols-2"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#35d0e5]">{copy.beforeTitle}</p><h2 className="mt-5 text-4xl font-black text-white sm:text-5xl">{copy.trustIntro}</h2><div className="mt-10 grid gap-6 sm:grid-cols-2"><div><h3 className="font-black text-white">{copy.noAskTitle}</h3><ul className="mt-4 space-y-3 text-slate-400">{copy.noAsk.map((item) => <li key={item}>— {item}</li>)}</ul></div><div><h3 className="font-black text-white">{copy.patternsTitle}</h3><ul className="mt-4 space-y-3 text-slate-400">{copy.patterns.map((item) => <li key={item}>— {item}</li>)}</ul></div></div></div><aside className="rounded-[2rem] border border-[#ff9a3d]/25 bg-[#ff9a3d]/[.035] p-7 sm:p-9"><p className="font-mono text-xs uppercase tracking-[.2em] text-[#ffbd7c]">Privacy + boundary</p><p className="mt-5 text-2xl font-black text-white">{copy.noBank}<br />{copy.noAi}</p><p className="mt-6 leading-7 text-slate-300">{copy.safetyBoundary}</p><p className="mt-6 text-sm leading-6 text-slate-500">{copy.localNotice}</p><Link href={localizeHref("/privacy#money-profile", locale)} className="mt-6 inline-flex min-h-11 items-center font-bold text-[#35d0e5]">{copy.privacyLink} →</Link></aside></section>
    <p className="py-8 text-sm leading-6 text-slate-500">{copy.contentLanguageNotice}</p>
  </div></article>;
}

function MoneyQuestionView({ answer, copy, currentIndex, onAnswer, onBack, onNext, onReset, onSkip, question, total }: { answer?: MoneyAnswer; copy: ReturnType<typeof getMoneyProfileUiCopy>; currentIndex: number; onAnswer: (answer: MoneyAnswer) => void; onBack: () => void; onNext: () => void; onReset: () => void; onSkip: () => void; question: MoneyQuestion; total: number }) {
  const values = answer?.skipped ? [] : Array.isArray(answer?.value) ? answer.value : answer?.value ? [answer.value] : [];
  const multiple = question.type === "multi";
  const answered = values.length > 0;
  const remainingMinutes = Math.max(1, Math.ceil((Math.max(0, total - currentIndex) * 20) / 60));
  return <article className="section-lines min-h-screen px-5 pb-24 pt-28 sm:px-8"><div className="mx-auto max-w-5xl"><MoneyJourneyHeader chapter={`${String(question.chapter).padStart(2, "0")} / 07 — ${moneyChapters[question.chapter - 1]}`} copy={copy} progress={(currentIndex + 1) / Math.max(total, 1)} remaining={`${remainingMinutes} min ${copy.remaining}`} onReset={onReset} />
    <main className="py-14 sm:py-20" lang="en"><p className="font-mono text-xs font-black uppercase tracking-[.22em] text-[#b8a5ff]">{question.id.toUpperCase()} · {question.title}</p>{question.chapter === 5 ? <p className="mt-5 max-w-3xl rounded-xl border border-[#ff9a3d]/20 bg-[#ff9a3d]/[.035] p-4 leading-7 text-slate-300">Money can change our behaviour when it starts feeling threatening. These questions are about that shift — not who you are all the time.</p> : null}<h1 className="mt-7 max-w-4xl text-4xl font-black leading-tight text-white sm:text-6xl">{question.prompt}</h1>{question.instruction ? <p className="mt-5 max-w-3xl leading-7 text-slate-400">{question.instruction}</p> : null}<fieldset className="mt-10"><legend className="sr-only">{multiple ? copy.chooseSeveral : copy.chooseOne}</legend><p className="mb-4 font-mono text-xs uppercase tracking-[.18em] text-slate-500">{multiple ? copy.chooseSeveral : copy.chooseOne}{multiple && question.maxSelections ? ` · ${values.length}/${question.maxSelections} ${copy.selected}` : ""}</p><div className="grid gap-3">{question.options.map((option) => { const selected = values.includes(option.id); const atLimit = multiple && !selected && values.length >= (question.maxSelections ?? question.options.length); return <button key={option.id} type="button" role={multiple ? "checkbox" : "radio"} aria-checked={selected} disabled={atLimit} onClick={() => { if (!multiple) onAnswer({ value: option.id }); else onAnswer({ value: selected ? values.filter((id) => id !== option.id) : [...values, option.id] }); }} className={`min-h-14 rounded-2xl border px-5 py-4 text-left font-bold leading-6 transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#b8a5ff] ${selected ? "border-[#b8a5ff] bg-[#b8a5ff]/10 text-white" : "border-white/10 bg-white/[.025] text-slate-300 hover:border-white/25"} disabled:opacity-35`}><span className="mr-3 font-mono text-xs text-[#b8a5ff]">{selected ? "●" : "○"}</span>{option.label}</button>; })}</div></fieldset></main>
    <footer className="flex flex-col-reverse gap-3 border-t border-white/15 pt-7 sm:flex-row sm:items-center"><button type="button" onClick={onBack} disabled={currentIndex === 0} className="min-h-12 rounded-full border border-white/15 px-6 font-bold text-slate-200 disabled:opacity-30">← {copy.back}</button><button type="button" onClick={onSkip} className="min-h-12 rounded-full px-5 text-sm font-bold text-slate-400 hover:text-white">{answer?.skipped ? copy.skipped : copy.skip}</button><button type="button" onClick={onNext} disabled={!answered && !answer?.skipped} className="min-h-12 rounded-full bg-[#b8a5ff] px-7 font-black text-[#041018] disabled:cursor-not-allowed disabled:opacity-35 sm:ml-auto">{copy.next} →</button></footer>
  </div></article>;
}

function MoneyJourneyHeader({ chapter, copy, onReset, progress, remaining }: { chapter: string; copy: ReturnType<typeof getMoneyProfileUiCopy>; onReset: () => void; progress: number; remaining?: string }) {
  return <header className="border-b border-white/15 py-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-xs font-black uppercase tracking-[.18em] text-[#b8a5ff]">{chapter}</p>{remaining ? <p className="mt-2 text-xs text-slate-500">{remaining} · {copy.localNotice}</p> : null}</div><button type="button" onClick={onReset} className="min-h-11 rounded-full border border-white/10 px-4 text-xs font-bold text-slate-400 hover:text-white">{copy.startOver}</button></div><div role="progressbar" aria-label={copy.progress} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress * 100)} className="mt-5 h-1 overflow-hidden rounded-full bg-white/10"><span className="block h-full bg-[#b8a5ff] transition-[width] motion-reduce:transition-none" style={{ width: `${Math.max(2, progress * 100)}%` }} /></div></header>;
}

function MoneyCalibrationView({ calibration, copy, hypotheses, onBack, onChange, onContinue, onReset }: { calibration: MoneyCalibration; copy: ReturnType<typeof getMoneyProfileUiCopy>; hypotheses: ReturnType<typeof generateMoneyCalibrationHypotheses>; onBack: () => void; onChange: (id: string, value: MoneyCalibrationValue) => void; onContinue: () => void; onReset: () => void }) {
  const complete = hypotheses.every(({ id }) => calibration[id]);
  return <article className="section-lines min-h-screen px-5 pb-24 pt-28 sm:px-8"><div className="mx-auto max-w-6xl"><MoneyJourneyHeader chapter={copy.calibrationEyebrow} copy={copy} progress={1} onReset={onReset} /><main className="py-14 sm:py-20"><h1 className="text-5xl font-black text-white sm:text-7xl">{copy.calibrationTitle}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">{copy.calibrationBody}</p><div className="mt-12 grid gap-6">{hypotheses.map((hypothesis, index) => <section key={hypothesis.id} className="rounded-[1.75rem] border border-white/10 bg-[#071824]/70 p-6 sm:p-8" lang="en"><p className="font-mono text-xs text-[#b8a5ff]">PATTERN {String.fromCharCode(65 + index)}</p><p className="mt-5 max-w-4xl text-2xl font-black leading-9 text-white">{hypothesis.text}</p><div className="mt-7 grid gap-2 sm:grid-cols-3">{(["very-true", "partly", "not-really"] as const).map((value) => <button key={value} type="button" role="radio" aria-checked={calibration[hypothesis.id] === value} onClick={() => onChange(hypothesis.id, value)} className={`min-h-12 rounded-full border px-4 font-bold ${calibration[hypothesis.id] === value ? "border-[#b8a5ff] bg-[#b8a5ff]/10 text-white" : "border-white/10 text-slate-300"}`}>{value === "very-true" ? copy.veryTrue : value === "partly" ? copy.partly : copy.notReally}</button>)}</div></section>)}</div></main><footer className="flex gap-3 border-t border-white/15 pt-7"><button type="button" onClick={onBack} className="min-h-12 rounded-full border border-white/15 px-6 font-bold text-white">← {copy.back}</button><button type="button" onClick={onContinue} disabled={!complete} className="ml-auto min-h-12 rounded-full bg-[#b8a5ff] px-7 font-black text-[#041018] disabled:opacity-35">{copy.connecting} →</button></footer></div></article>;
}

function MoneyReveal({ copy, onReveal }: { copy: ReturnType<typeof getMoneyProfileUiCopy>; onReveal: () => void }) {
  return <article className="relative grid min-h-screen place-items-center overflow-hidden px-5 py-28 text-center"><div aria-hidden="true" className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(184,165,255,.15),transparent_28rem)]" /><div className="relative max-w-4xl"><p className="font-mono text-xs font-black uppercase tracking-[.28em] text-[#b8a5ff]">{copy.connecting}</p><h1 className="mt-7 text-6xl font-black text-white sm:text-8xl">{copy.revealTitle}</h1><p className="mx-auto mt-7 max-w-2xl text-xl leading-8 text-slate-300">{copy.revealBody}</p><button type="button" onClick={onReveal} className="mt-10 min-h-14 rounded-full bg-[#b8a5ff] px-8 text-lg font-black text-[#041018]">{copy.reveal} →</button></div></article>;
}

function MoneyResult({ copy, formToken, locale, onRetake, onSelectExperiment, onShare, onShareClose, result, selectedExperiment, shareOpen }: { copy: ReturnType<typeof getMoneyProfileUiCopy>; formToken: string | null; locale: Locale; onRetake: () => void; onSelectExperiment: () => void; onShare: () => void; onShareClose: () => void; result: MoneyProfileResult; selectedExperiment: boolean; shareOpen: boolean }) {
  const profileLabel = result.primaryProfile ? `${result.primaryProfile.label}${result.secondaryProfile ? ` × ${result.secondaryProfile.label}` : ""}` : result.baseline.headline;
  return <article className="section-lines px-5 pb-24 pt-28 sm:px-8"><div className="mx-auto max-w-[90rem]" lang="en"><header id="money-profile" className="scroll-mt-28 min-h-[70svh] border-b border-white/15 py-16"><p className="font-mono text-xs font-black uppercase tracking-[.26em] text-[#b8a5ff]">{copy.profile}</p><h1 className="mt-7 max-w-6xl text-[clamp(3.5rem,9vw,8.2rem)] font-black leading-[.86] tracking-[-.065em] text-white">{profileLabel}</h1><p className="mt-8 max-w-4xl text-2xl font-bold leading-10 text-slate-200">{result.baseline.description}</p><p className="mt-8 inline-flex rounded-full border border-[#b8a5ff]/35 px-4 py-2 text-sm font-bold text-[#d5caff]">{copy.confidence[result.confidenceMode]}</p></header>
    <MoneyResultNavigation copy={copy} />
    <section id="money-meaning" className="scroll-mt-28 grid gap-10 border-b border-white/15 py-20 lg:grid-cols-[.38fr_1fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#ff9a3d]">Meta layer</p><h2 className="mt-5 text-5xl font-black text-white">{copy.meaning}</h2></div><div><div className="flex flex-wrap gap-3">{result.meanings.map(({ id, label }) => <span key={id} className="rounded-full border border-[#ff9a3d]/35 px-5 py-3 text-lg font-black text-[#ffcfaa]">{label}</span>)}</div><p className="mt-7 max-w-3xl leading-8 text-slate-300">These themes describe what money appears to represent in your answers. They interpret behaviour without inventing a cause.</p></div></section>
    <section id="money-baseline" className="scroll-mt-28 border-b border-white/15 py-20"><h2 className="text-5xl font-black text-white">Baseline → Stress</h2><div className="mt-10 grid gap-6 lg:grid-cols-2"><ResultPanel eyebrow={copy.baseline} title={result.baseline.headline} body={result.baseline.description} accent="#35d0e5" /><ResultPanel eyebrow={copy.underStress} title={result.stress.baselineShift.join(" · ") || "Context-dependent"} body={result.stress.description} accent="#ff9a3d" /></div></section>
    <section className="grid gap-12 border-b border-white/15 py-20 lg:grid-cols-2"><ResultList title={copy.works} items={result.strengths.length ? result.strengths : [result.playbook.atMyBest]} accent="#77e5b5" /><ResultList title={copy.blindSpots} items={result.blindSpots.length ? result.blindSpots : ["No repeated friction was strongly supported. Keep testing the map instead of inventing a problem."]} accent="#ff9a3d" /></section>
    <section id="money-tradeoffs" className="scroll-mt-28 border-b border-white/15 py-20"><h2 className="text-5xl font-black text-white">{copy.tradeOffs}</h2><div className="mt-10 grid gap-5 lg:grid-cols-2">{result.tensions.length ? result.tensions.map((tension) => <ResultPanel key={tension.id} eyebrow={tension.dimensionIds.map((id) => result.dimensions.find(({ dimension }) => dimension.id === id)?.dimension.label).join(" × ")} title={tension.insight} body={tension.tradeOff} accent="#b8a5ff" />) : <p className="max-w-3xl leading-8 text-slate-300">No tension was strong enough to present as a stable pattern. That is a valid result.</p>}</div></section>
    <section className="grid gap-12 border-b border-white/15 py-20 lg:grid-cols-2"><ResultList title={copy.triggers} items={result.triggers.length ? result.triggers : ["No recurring trigger was strongly supported."]} accent="#ff9a3d" /><div><h2 className="text-4xl font-black text-white">{copy.helps}</h2><div className="mt-7 space-y-5">{result.interventions.map((item) => <article key={item.id} className="rounded-2xl border border-white/10 p-6"><h3 className="text-2xl font-black text-white">{item.label}</h3><p className="mt-3 leading-7 text-slate-300">{item.fitReason}</p><p className="mt-3 text-sm leading-6 text-slate-500">{item.concept}</p></article>)}</div></div></section>
    <section id="money-playbook" className="scroll-mt-28 border-b border-white/15 py-20"><h2 className="text-5xl font-black text-white sm:text-7xl">{copy.playbook}</h2><div className="mt-12 grid gap-6 lg:grid-cols-2"><ResultPanel eyebrow={copy.atMyBest} title={result.playbook.atMyBest} body={result.baseline.description} accent="#77e5b5" /><ResultPanel eyebrow={copy.underStress} title={result.stress.baselineShift.join(" · ") || "Context-dependent"} body={result.playbook.underStress} accent="#ff9a3d" /><ResultList title={copy.watchFor} items={result.playbook.watchFor} accent="#b8a5ff" /><ResultList title={copy.whatHelps} items={result.playbook.whatHelps} accent="#35d0e5" /></div><div className="mt-8 rounded-[1.5rem] border border-[#77e5b5]/25 p-7"><p className="font-mono text-xs uppercase tracking-[.2em] text-[#77e5b5]">{copy.myNextMove}</p><p className="mt-4 text-2xl font-black leading-9 text-white">{result.playbook.myNextMove}</p></div></section>
    <section className="grid gap-12 border-b border-white/15 py-20 lg:grid-cols-[.38fr_1fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#35d0e5]">{copy.nextSteps}</p><h2 className="mt-5 text-5xl font-black text-white">3–5 small moves</h2></div><ol className="space-y-5">{result.nextSteps.map((step, index) => <li key={step} className="flex gap-5 rounded-2xl border border-white/10 p-6"><span className="font-mono text-xs text-[#35d0e5]">0{index + 1}</span><p className="leading-7 text-slate-300">{step}</p></li>)}</ol></section>
    <section className="border-b border-white/15 py-20"><p className="font-mono text-xs uppercase tracking-[.2em] text-[#b8a5ff]">Money Experiment</p><h2 className="mt-5 text-5xl font-black text-white">{copy.experiment}</h2><p className="mt-7 max-w-4xl text-xl leading-9 text-slate-300">{result.experiment}</p><button type="button" aria-pressed={selectedExperiment} onClick={onSelectExperiment} className={`mt-8 min-h-12 rounded-full border px-6 font-bold ${selectedExperiment ? "border-[#b8a5ff] bg-[#b8a5ff]/10 text-white" : "border-white/15 text-slate-300"}`}>{selectedExperiment ? "Selected" : "Test this"}</button></section>
    <section id="money-onepager" className="scroll-mt-28 py-20"><MoneyOnePager copy={copy} result={result} onShare={onShare} /><div className="mx-auto mt-12 max-w-3xl text-center"><p className="text-xl font-bold leading-8 text-slate-200">{copy.closing}</p><p className="mt-5 text-sm leading-6 text-slate-500">{copy.boundaryShort}</p><button type="button" onClick={onRetake} className="mt-8 min-h-12 rounded-full border border-white/15 px-6 font-bold text-white">{copy.retake}</button></div></section>
    <ResultFeedback formToken={formToken} locale={locale} product="money-profile" showSensitiveFinancialWarning onOpened={() => emitMoneyProfileEvent("money_profile_feedback_opened")} onSubmitted={() => emitMoneyProfileEvent("money_profile_feedback_submitted")} />
  </div>{shareOpen ? <MoneyProfileShareDialog copy={copy} result={result} onClose={onShareClose} /> : null}</article>;
}

function MoneyResultNavigation({ copy }: { copy: ReturnType<typeof getMoneyProfileUiCopy> }) {
  const links = [["money-profile", copy.profile], ["money-meaning", copy.meaning], ["money-baseline", copy.baseline], ["money-tradeoffs", copy.tradeOffs], ["money-playbook", copy.playbook], ["money-onepager", copy.onePager]];
  return <nav aria-label="Money Profile" className="sticky top-20 z-20 -mx-5 overflow-x-auto border-b border-white/10 bg-[#04111b]/92 px-5 backdrop-blur-xl sm:-mx-8 sm:px-8"><ul className="mx-auto flex min-w-max max-w-[90rem] gap-1 py-2">{links.map(([id, label]) => <li key={id}><a href={`#${id}`} className="inline-flex min-h-11 items-center rounded-full px-4 text-sm font-bold text-slate-400 hover:bg-white/5 hover:text-white">{label}</a></li>)}</ul></nav>;
}

function ResultPanel({ accent, body, eyebrow, title }: { accent: string; body: string; eyebrow: string; title: string }) {
  return <article className="rounded-[1.5rem] border border-white/10 p-6 sm:p-8" style={{ borderTopColor: accent, borderTopWidth: 2 }}><p className="font-mono text-xs uppercase tracking-[.18em]" style={{ color: accent }}>{eyebrow}</p><h3 className="mt-5 text-2xl font-black leading-9 text-white">{title}</h3><p className="mt-4 leading-7 text-slate-300">{body}</p></article>;
}

function ResultList({ accent, items, title }: { accent: string; items: readonly string[]; title: string }) {
  return <section><h2 className="text-4xl font-black text-white">{title}</h2><ul className="mt-7 space-y-4">{items.map((item) => <li key={item} className="border-l-2 pl-5 leading-7 text-slate-300" style={{ borderColor: accent }}>{item}</li>)}</ul></section>;
}

function MoneyOnePager({ copy, onShare, result }: { copy: ReturnType<typeof getMoneyProfileUiCopy>; onShare: () => void; result: MoneyProfileResult }) {
  const label = result.primaryProfile ? `${result.primaryProfile.label}${result.secondaryProfile ? ` × ${result.secondaryProfile.label}` : ""}` : result.baseline.headline;
  return <section className="mx-auto max-w-5xl rounded-[2rem] border border-[#b8a5ff]/25 bg-[linear-gradient(145deg,#071824,#0b1725)] p-7 shadow-2xl sm:p-12"><header className="flex flex-wrap justify-between gap-4 border-b border-white/15 pb-6"><p className="font-mono text-xs font-black uppercase tracking-[.22em] text-[#b8a5ff]">{copy.onePager}</p><p className="font-mono text-xs text-slate-500">Money Profile · bts.online</p></header><div className="py-10"><p className="font-mono text-xs uppercase tracking-[.18em] text-slate-500">{copy.profile}</p><h2 className="mt-4 text-5xl font-black leading-none text-white sm:text-7xl">{label}</h2><p className="mt-6 text-lg font-bold text-[#ffcfaa]">{result.meanings.slice(0, 4).map(({ id }) => moneyMeaningLabels[id]).join(" · ")}</p></div><div className="grid gap-7 border-y border-white/10 py-8 md:grid-cols-2"><ResultList title={copy.atMyBest} items={[result.playbook.atMyBest]} accent="#77e5b5" /><ResultList title={copy.underStress} items={[result.stress.primary ? `${moneyStressResponseLabels[result.stress.primary]} ↑` : "Context-dependent"]} accent="#ff9a3d" /><ResultList title={copy.watchFor} items={result.playbook.watchFor.slice(0, 1)} accent="#b8a5ff" /><ResultList title={copy.whatHelps} items={result.interventions.slice(0, 3).map(({ label: item }) => item)} accent="#35d0e5" /><ResultList title={copy.myNextMove} items={[result.playbook.myNextMove]} accent="#77e5b5" /></div><button type="button" onClick={() => { emitMoneyProfileEvent("money_profile_onepager_opened"); onShare(); }} className="mt-8 min-h-12 rounded-full bg-[#b8a5ff] px-7 font-black text-[#041018]">{copy.share} →</button></section>;
}
