"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState, useTransition } from "react";

import { acknowledgeRelationshipAgreementAction, deleteRelationshipParticipationAction, revokeRelationshipInviteAction, saveRelationshipAgreementAction, saveRelationshipAnswersAction, type RelationshipActionResult } from "@/app/life-alignment/actions";
import { useLocale, useLocalizedHref } from "@/components/i18n/locale-context";
import { useRelationshipPrintMode } from "@/components/life-alignment/relationship/relationship-print-mode";
import { relationshipText } from "@/data/life-alignment-relationship";
import { relationshipSessionUi } from "@/data/i18n/life-alignment-relationship-session-ui";
import { relationshipUi } from "@/data/i18n/life-alignment-relationship-ui";
import { getRelationshipCategoryLabel } from "@/lib/life-alignment-relationship";
import type { RelationshipAnswer, RelationshipModuleDefinition, RelationshipSessionView } from "@/types/life-alignment-relationship";

const idle: RelationshipActionResult = { ok: false, code: "INVALID_REQUEST" };

export function RelationshipSessionExperience({ module, view }: { module: RelationshipModuleDefinition; view: RelationshipSessionView }) {
  const locale = useLocale(); const router = useRouter(); const [pending,startTransition]=useTransition();
  const [answers,setAnswers]=useState<Record<string,RelationshipAnswer>>(view.ownAnswers as Record<string,RelationshipAnswer>); const [sectionIndex,setSectionIndex]=useState(0); const [message,setMessage]=useState<string|null>(null);
  const section=module.sections[sectionIndex]!; const questions=useMemo(()=>module.questions.filter(({sectionId})=>sectionId===section.id),[module.questions,section.id]);
  if (view.ownStatus !== "completed") {
    const next=()=>{ if(!questions.every((question)=>question.optional||answers[question.id])){setMessage(relationshipUi(locale,"answerRequired"));return;} const final=sectionIndex===module.sections.length-1; startTransition(async()=>{const form=new FormData();form.set("sessionId",view.sessionId);form.set("moduleId",module.id);form.set("answers",JSON.stringify(answers));form.set("complete",final?"yes":"no");const result=await saveRelationshipAnswersAction(idle,form);if(!result.ok){setMessage(relationshipUi(locale,"saveFailed"));return;}if(final){router.refresh();return;}setSectionIndex((value)=>value+1);setMessage(relationshipUi(locale,"saved"));window.scrollTo({top:0,behavior:"smooth"});});};
    return <article className="section-lines min-h-screen px-5 pb-40 pt-28 sm:px-8 sm:pt-36"><div className="mx-auto max-w-5xl"><header className="border-b border-white/15 pb-10"><p className="font-mono text-xs font-black uppercase tracking-[0.2em] text-[#74d8c8]">{relationshipUi(locale,"privateInvite")} · {relationshipUi(locale,"independentFirst")}</p><h1 className="mt-5 text-4xl font-black text-white sm:text-6xl">{relationshipText(section.title,locale)}</h1><p className="mt-4 leading-7 text-slate-300">{relationshipUi(locale,"answersPrivate")}</p></header><div className="mt-9 grid gap-5">{questions.map((question)=><fieldset key={question.id} className="rounded-2xl border border-white/10 p-6"><legend className="px-2 text-xl font-black text-white">{relationshipText(question.prompt,locale)}</legend><div className="mt-6 grid grid-cols-5 gap-2">{([1,2,3,4,5] as const).map((value)=><label key={value} className={`flex min-h-12 cursor-pointer items-center justify-center rounded-xl border font-black ${answers[question.id]?.value===value?"border-[#74d8c8] bg-[#74d8c8]/15 text-white":"border-white/15 text-slate-300"}`}><input type="radio" className="sr-only" name={`${question.id}-value`} checked={answers[question.id]?.value===value} onChange={()=>setAnswers((current)=>({...current,[question.id]:{value,importance:current[question.id]?.importance??"medium"}}))}/>{value}</label>)}</div><div className="mt-3 flex justify-between text-xs text-slate-400"><span>{relationshipText(question.leftLabel,locale)}</span><span>{relationshipText(question.rightLabel,locale)}</span></div><p className="mt-5 text-sm font-black text-slate-300">{relationshipUi(locale,"importance")}</p><div className="mt-2 flex gap-2">{(["low","medium","high"] as const).map((importance)=><label key={importance} className={`cursor-pointer rounded-full border px-4 py-2 text-sm ${answers[question.id]?.importance===importance?"border-[#f5b971] text-white":"border-white/15 text-slate-400"}`}><input type="radio" className="sr-only" name={`${question.id}-importance`} checked={answers[question.id]?.importance===importance} onChange={()=>setAnswers((current)=>({...current,[question.id]:{value:current[question.id]?.value??3,importance}}))}/>{relationshipUi(locale,importance)}</label>)}</div></fieldset>)}</div>{message?<p role="alert" className="mt-6 text-[#ffd5a1]">{message}</p>:null}<nav className="fixed inset-x-0 bottom-0 border-t border-white/10 bg-[#04121c]/95 p-4"><div className="mx-auto flex max-w-5xl justify-between"><button disabled={sectionIndex===0||pending} onClick={()=>setSectionIndex((value)=>value-1)} className="min-h-12 rounded-full border border-white/20 px-6 text-white disabled:opacity-40">{relationshipUi(locale,"back")}</button><button disabled={pending} onClick={next} className="min-h-12 rounded-full bg-[#74d8c8] px-7 font-black text-[#04151d]">{sectionIndex===module.sections.length-1?relationshipUi(locale,"finish"):relationshipUi(locale,"continue")}</button></div></nav></div></article>;
  }
  if (!view.sharedResultAvailable || !view.sharedResult) return <Waiting view={view}/>;
  return <SharedResult module={module} view={view}/>;
}

function Waiting({view}:{view:RelationshipSessionView}) {
  const locale=useLocale(); const localizeHref=useLocalizedHref(); const copy=relationshipSessionUi(locale); const router=useRouter(); const [pending,startTransition]=useTransition(); const [message,setMessage]=useState<string|null>(null);
  const run=(action:()=>Promise<RelationshipActionResult>,onSuccess:()=>void)=>startTransition(async()=>{const result=await action();if(result.ok)onSuccess();else setMessage(result.code);});
  return <article className="section-lines min-h-screen px-5 pb-24 pt-32"><div className="mx-auto max-w-3xl rounded-[2rem] border border-[#74d8c8]/30 p-8 sm:p-12"><h1 className="text-5xl font-black text-white">{relationshipUi(locale,"waitingTitle")}</h1><p className="mt-6 text-lg leading-8 text-slate-300">{relationshipUi(locale,"waitingBody")}</p><p className="mt-4 text-sm text-slate-500">{copy.otherParticipant}: {copy.status[view.counterpartStatus]}.</p><div className="mt-8 flex flex-wrap gap-3">{view.viewerRole==="invitee"?<button disabled={pending} onClick={()=>run(()=>deleteRelationshipParticipationAction(view.sessionId),()=>router.push(localizeHref("/life-alignment")))} className="min-h-11 rounded-full border border-[#ffb36d]/40 px-5 font-bold text-[#ffd3a8]">{copy.deleteParticipation}</button>:null}{view.viewerRole==="initiator"&&view.inviteStatus==="active"?<button disabled={pending} onClick={()=>run(()=>revokeRelationshipInviteAction(view.sessionId),()=>router.refresh())} className="min-h-11 rounded-full border border-[#ffb36d]/40 px-5 font-bold text-[#ffd3a8]">{copy.revokeInvite}</button>:null}</div>{message?<p role="alert" className="mt-4 text-[#ffd3a8]">{message}</p>:null}</div></article>;
}

function SharedResult({module,view}:{module:RelationshipModuleDefinition;view:RelationshipSessionView}) {
  const locale=useLocale(); useRelationshipPrintMode(); const copy=relationshipSessionUi(locale);
  return <article data-fyns-result-page className="section-lines px-5 pb-24 pt-28 sm:px-8 sm:pt-36"><div className="mx-auto max-w-6xl" data-fyns-result-page-content><header className="border-b border-white/15 pb-12"><p className="font-mono text-xs font-black uppercase tracking-[0.2em] text-[#74d8c8]">{relationshipText(module.title,locale)} · {relationshipUi(locale,"sharedAfterwards")}</p><h1 className="mt-5 text-5xl font-black text-white sm:text-7xl">{copy.sharedTitle}</h1><p className="mt-6 max-w-4xl leading-7 text-slate-300">{relationshipUi(locale,"noScore")} {copy.sharedEvidence}</p></header><div className="mt-10 grid gap-5">{view.sharedResult!.insights.map((insight)=><section key={insight.id} className="rounded-2xl border border-white/10 p-6"><p className="font-mono text-xs font-black uppercase tracking-[0.15em] text-[#74d8c8]">{getRelationshipCategoryLabel(insight.category,locale)}</p><h2 className="mt-3 text-2xl font-black text-white">{insight.title}</h2><p className="mt-4 leading-7 text-slate-300">{insight.explanation}</p><h3 className="mt-5 font-black text-white">{relationshipUi(locale,"whatThisCouldMean")}</h3><p className="mt-2 leading-7 text-slate-400">{insight.whatThisCouldMean}</p><h3 className="mt-5 font-black text-white">{relationshipUi(locale,"talkAboutThis")}</h3><p className="mt-2 leading-7 text-slate-400">{insight.talkAboutThis}</p><h3 className="mt-5 font-black text-white">{relationshipUi(locale,"tryThis")}</h3><p className="mt-2 leading-7 text-slate-400">{insight.tryThis}</p></section>)}</div><AgreementPanel view={view}/><button onClick={()=>window.print()} className="mt-10 min-h-12 rounded-full bg-[#f5b971] px-6 font-black text-[#07131d]">{relationshipUi(locale,"print")}</button><section aria-hidden="true" className="fyns-print-document" data-fyns-print-document="life-alignment-relationship-shared"><header className="fyns-print-header"><p className="fyns-print-brand">Life Alignment · {relationshipText(module.title,locale)} · {copy.round} {view.roundNumber}</p><h1>{copy.sharedAlignment}</h1></header>{view.sharedResult!.insights.map((insight)=><section className="fyns-print-section" key={insight.id}><h2>{insight.title}</h2><p>{insight.explanation}</p><p><strong>{relationshipUi(locale,"talkAboutThis")}:</strong> {insight.talkAboutThis}</p><p><strong>{relationshipUi(locale,"tryThis")}:</strong> {insight.tryThis}</p></section>)}{view.agreement?.status==="finalized"?<section className="fyns-print-section"><h2>{copy.finalizedAgreements}</h2><ol>{view.agreement.items.map((item)=><li key={item}>{item}</li>)}</ol><p>{copy.agreementLegal}</p></section>:null}</section></div></article>;
}

function AgreementPanel({view}:{view:RelationshipSessionView}) {
  const locale=useLocale(); const copy=relationshipSessionUi(locale); const router=useRouter(); const [items,setItems]=useState<string[]>(view.agreement?.items.length?[...view.agreement.items]:[""]); const [pending,startTransition]=useTransition(); const [message,setMessage]=useState<string|null>(null);
  const save=()=>startTransition(async()=>{const form=new FormData();form.set("sessionId",view.sessionId);form.set("revision",String(view.agreement?.revision??0));items.forEach((item)=>form.append("items",item));const result=await saveRelationshipAgreementAction(idle,form);if(result.ok)router.refresh();else setMessage(result.code);});
  const acknowledge=()=>{if(!view.agreement)return;startTransition(async()=>{const result=await acknowledgeRelationshipAgreementAction(view.sessionId,view.agreement!.revision);if(result.ok)router.refresh();else setMessage(result.code);});};
  return <section className="mt-12 rounded-[2rem] border border-[#f5b971]/30 bg-[#f5b971]/[0.04] p-7 sm:p-10"><h2 className="text-3xl font-black text-white">{relationshipUi(locale,"createAgreement")}</h2><p className="mt-4 leading-7 text-slate-300">{copy.agreementDescription}</p><div className="mt-6 grid gap-3">{items.map((item,index)=><div key={index} className="flex gap-2"><input value={item} maxLength={240} onChange={(event)=>setItems((current)=>current.map((value,itemIndex)=>itemIndex===index?event.target.value:value))} className="min-h-12 flex-1 rounded-xl border border-white/15 bg-[#03101a] px-4 text-white"/><button type="button" disabled={items.length===1} onClick={()=>setItems((current)=>current.filter((_,itemIndex)=>itemIndex!==index))} className="rounded-xl border border-white/15 px-4 text-white disabled:opacity-30">×</button></div>)}</div>{items.length<5?<button type="button" onClick={()=>setItems((current)=>[...current,""])} className="mt-4 text-sm font-bold text-[#f5b971]">+ {copy.addItem}</button>:null}<div className="mt-6 flex flex-wrap gap-3"><button disabled={pending} onClick={save} className="min-h-11 rounded-full bg-[#f5b971] px-5 font-black text-[#07131d]">{copy.saveDraft}</button>{view.agreement&&!view.agreement.acknowledgedByViewer?<button disabled={pending} onClick={acknowledge} className="min-h-11 rounded-full border border-[#74d8c8]/50 px-5 font-black text-[#74d8c8]">{copy.acknowledge(view.agreement.revision)}</button>:null}</div>{view.agreement?<p className="mt-4 text-sm text-slate-400">{copy.state}: {copy.status[view.agreement.status]} · {copy.revision} {view.agreement.revision}. {copy.editResets}</p>:null}{message?<p role="alert" className="mt-4 text-[#ffd3a8]">{message}</p>:null}</section>;
}
